openapi: 3.1.0
info:
  version: 1.0.0
  title: Hamal Api Title
  description: Hamal API description
  termsOfService: https://hamal.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://hamal.io
tags:
  - name: Blueprint
    description: Endpoints to manage Blueprint Actions using the REST API.
  - name: Func
    description: To come
paths:
  /v1/groups/{groupId}/blueprints:
    $ref: paths/blueprint_create.yaml
  /v1/blueprints/{bpId}:
    $ref: paths/blueprint_get_patch.yaml

security:
  - JWT: [ ]

components:
  securitySchemes:
    JWT:
      $ref: components/securitySchemes/JWT.yaml

    