--sys = require_plugin('std.sys')
--
--topics = fail_on_error(sys.topics.list())
--assert(#topics == 0)
--
--topic_req = fail_on_error(sys.topics.append({ name = "topic-one" }))
--sys.await(topic_req)
--
--topics = fail_on_error(sys.topics.list())
--assert(#topics == 1)
--assert(topics[1].name == 'topic-one')