--sys = require_plugin('std.sys')
--
--topic_req = fail_on_error(sys.topics.append({ name = "some-amazing-topic" }))
--assert(topic_req.id ~= nil)
--assert(topic_req.request_status == 'Submitted')
--assert(topic_req.topic_id ~= nil)
--assert(topic_req.workspace_id == '539')
--sys.await(topic_req)
--
--topic_id = fail_on_error(sys.topics.get(topic_req.topic_id))
--assert(topic_id.id == topic_req.topic_id)
--assert(topic_id.name == 'some-amazing-topic')