version: "3.5"
services:
  backend:
    image: hamalio/hamal-backend
    ports:
      - "0.0.0.0:8008:8008"
    environment:
      - ACTIVE_PROFILES=default,memory,dev
    networks:
      - hamalnet

  runner:
    image: hamalio/hamal-runner
    environment:
      - ACTIVE_PROFILES=default,dev
      - API_HOST=http://backend:8008
      - BRIDGE_HOST=http://backend:7007
    networks:
      - hamalnet
    depends_on:
      backend:
        condition: service_started

networks:
  hamalnet: