version: "3.5"
services:
  backend:
    image: hamalio/hamal-backend
    ports:
      - "0.0.0.0:9009:9009"
    environment:
      - ACTIVE_PROFILES=default,memory
    networks:
      - hamalnet

  runner:
    image: hamalio/hamal-runner
    environment:
      - ACTIVE_PROFILES=default
      - ADMIN_HOST=http://backend:9009
      - API_HOST=http://backend:8008
      - BRIDGE_HOST=http://backend:7007
    networks:
      - hamalnet
    depends_on:
      backend:
        condition: service_started

networks:
  hamalnet: