version: "3.5"
services:
  mono:
    image: hamalio/hamal-mono
    restart:
      unless-stopped
    ports:
      - "0.0.0.0:9009:9009"
    environment:
      - ACTIVE_PROFILES=default,memory
    networks:
      - hamal_net
  fn-guru:
    image: hamalio/fn-guru
    restart:
      unless-stopped
    ports:
      - "0.0.0.0:6006:6006"
    environment:
      - ACTIVE_PROFILES=default
      - HUB_HOST=http://hamal:8008
    networks:
      - hamal_net

networks:
  hamal_net:
