logging:
  level:
    root: INFO
    io.hamal: INFO
    io.hamal.runner: DEBUG
    io.hamal.repository: INFO
    io.hamal.repository.sqlite.log: INFO
    io.hamal.extension.web3: TRACE
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC

  profiles:
    active: ${ACTIVE_PROFILES:default}

server:
  tomcat:
    threads:
      max: 10
      min-spare: 2


io:
  hamal:
    runner:
      admin:
        host: ${ADMIN_HOST:http://127.0.0.1:9009}
      api:
        host: ${API_HOST:http://127.0.0.1:8008}
      bridge:
        host: ${BRIDGE_HOST:http://127.0.0.1:7007}