version: "3.5"
services:
  backend:
    image: hamalio/hamal-backend
    ports:
      - "0.0.0.0:8008:8008"
    environment:
      - ACTIVE_PROFILES=default,sqlite,dev
    volumes:
      - "/tmp/hamal/backend:/tmp/hamal/backend"
    networks:
      - hamal_net

  runner:
    image: hamalio/hamal-runner
    environment:
      - ACTIVE_PROFILES=default,dev
      - API_HOST=http://backend:8008
      - BRIDGE_HOST=http://backend:7007
      - HTTP_POLL_EVERY_MS=100
    networks:
      - hamal_net
    depends_on:
      backend:
        condition: service_started

networks:
  hamal_net: