version: "3.5"
services:
  mono:
    image: hamalio/hamal-mono
    restart:
      unless-stopped
    ports:
      - "0.0.0.0:8008:8008"
    environment:
      - ACTIVE_PROFILES=default,memory
    networks:
      - hamal_net

networks:
  hamal_net: