logging:
  level:
    root: INFO
    io.hamal: INFO
    io.hamal.runner: DEBUG
    io.hamal.repository: INFO
    io.hamal.extension: INFO
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC

  profiles:
    active: ${ACTIVE_PROFILES:default}

io:
  hamal:
    instance: ${INSTANCE:1}