logging:
  level:
    root: WARN
    io.hamal: INFO
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
server:
  tomcat:
    threads:
      max: 2
      min-spare: 1
  port: 10000

io:
  hamal:
    proxy:
      upstream:
        host: ${UPSTREAM_HOST:http://localhost:10001}