logging:
  level:
    root: WARN
    io.hamal: INFO
    #    io.hamal.backend.repository: DEBUG
    io.hamal.backend.repository: INFO
    io.hamal.backend.repository.sqlite.log: INFO
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
server:
  port: 8000

io:
  hamal:
    proxy:
      upstream: ${PROXY_UPSTREAM:https://cloudflare-eth.com}