name: Run CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gradle:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Setup
        uses: gradle/gradle-build-action@v2

      - name: Assemble
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew check

      - name: Generate report
        run: ./gradlew integrationTestCodeCoverageReport

      - name: Upload coverage report
        uses: actions/checkout@v3
        with:
          repository: hamal-io/code-cov
          token: ${{ secrets.SERVICE_TOKEN }}
          fetch-depth: 0
          path: 'code-cov'
      - run: |
          cd code-cov
          rm -rf *
          cp -r ${{github.workspace}}/faas/bootstrap/build/reports/jacoco/integrationTestCodeCoverageReport/html/* .
          git add -A
          git config user.email "code-cov@hamal.io"
          git config user.name "code cov"
          git commit -m "${{ github.sha }}"
          git push -f
          