name: Run CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Setup
        uses: gradle/gradle-build-action@v2

      - name: Assemble
        run: ./gradlew assemble

      - name: Unit Test
        run: ./gradlew testCodeCoverageReport

      - name: Prepare coverage report
        uses: actions/checkout@v3
        with:
          repository: hamal-io/code-cov
          token: ${{ secrets.SERVICE_TOKEN }}
          fetch-depth: 0
          path: 'code-cov'
      - run: |
          cd code-cov
          rm -rf *
          cp -r ${{github.workspace}}/bootstrap/build/reports/jacoco .
          git add -A
          git config user.email "code-cov@hamal.io"
          git config user.name "code cov"
          git commit -m "c"
          git push -f