name: Run CI
on:
  push:
  workflow_dispatch:

jobs:
  gradle:
    timeout-minutes: 12
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Setup
        uses: gradle/gradle-build-action@v2

      - name: Assemble
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew check

      - name: Generate report
        if: github.ref == 'refs/heads/main'
        run: ./gradlew integrationTestCodeCoverageReport

      - name: Upload coverage report
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v3
        with:
          repository: hamal-io/code-cov
          token: ${{ secrets.SERVICE_TOKEN }}
          fetch-depth: 0
          path: 'code-cov'
          run: |
            cd code-cov
            rm -rf *
            cp -r ${{github.workspace}}/app/hamal-mono/build/reports/jacoco/integrationTestCodeCoverageReport/html/* .
            git add -A
            git config user.email "codecov@hamal.io"
            git config user.name "codecov"
            git commit -m "${{ github.sha }}"
            git push -f
